export const REQUEST_START = 'REQUEST_START'

//register and login action types
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT = 'LOGOUT';

// view recipe
export const GET_ALL_RECIPES_SUCCESS = 'GET_ALL_RECIPES_SUCCESS';
export const GET_ALL_RECIPES_FAILURE = 'GET_ALL_RECIPES_FAILURE';

//add ingredient
export const ADD_INGREDIENT_SUCCESS = 'ADD_INGREDIENT_SUCCESS';
export const ADD_INGREDIENT_FAILURE = 'ADD_INGREDIENT_FAILURE';

//view ingredients
export const GET_INGREDIENT_SUCCESS = 'GET_INGREDIENT_SUCCESS';
export const GET_INGREDIENT_FAILURE = 'GET_INGREDIENT_FAILURE';
export const RESET_DISPLAYED_INGREDIENTS = 'RESET_DISPLAYED_INGREDIENTS'

//create recipe 
export const  ADD_RECIPE_SUCCESS = 'ADD_RECIPE_SUCCESS';
export const ADD_RECIPE_FAILURE = 'ADD_RECIPE_FAILURE';
